#****************************************************************************
#*                                                                          *
#*   heapsOstuff Workbench:                                                 *
#*       few tools for better handling the merge of drawings                *
#*   Copyright (c) 2017 Riccardo Treu LGPL                                  *
#*                                                                          *
#*   This program is free software; you can redistribute it and/or modify   *
#*   it under the terms of the GNU Lesser General Public License (LGPL)     *
#*   as published by the Free Software Foundation; either version 2 of      *
#*   the License, or (at your option) any later version.                    *
#*   for detail see the LICENCE text file.                                  *
#*                                                                          *
#*   This program is distributed in the hope that it will be useful,        *
#*   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
#*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
#*   GNU Library General Public License for more details.                   *
#*                                                                          *
#*   You should have received a copy of the GNU Library General Public      *
#*   License along with this program; if not, write to the Free Software    *
#*   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307   *
#*   USA                                                                    *
#*                                                                          *
#****************************************************************************

class heapsOstuffWorkbench ( Workbench ):
  import DraftSnap
  Icon = '''
/* XPM */
static char * image[] = 
{
"43 43 152 2",
"AA c #002CA8",
"AB c #0431A8",
"AC c #0936A9",
"AD c #0B3AA8",
"AE c #113EAC",
"AF c #163FB0",
"AG c #0F40A9",
"AH c #1445A9",
"AI c #1649A9",
"AJ c #1944AF",
"AK c #194CA9",
"AL c #1B43B2",
"AM c #1E52AA",
"AN c #204EAF",
"AO c #254AB4",
"AP c #2155AB",
"AQ c #245BAA",
"AR c #295CAE",
"AS c #2E55B6",
"AT c #2F58B5",
"AU c #3151A7",
"AV c #3C59AC",
"AW c #3053B9",
"AX c #315BB6",
"AY c #375FBC",
"AZ c #3A5DBB",
"BA c #2B64AA",
"BB c #3465A4",
"BC c #316EA0",
"BD c #3268AE",
"BE c #3A69A7",
"BF c #3E6EAA",
"BG c #3B67B6",
"BH c #3F60BD",
"BI c #3E6DB6",
"BJ c #3D71B2",
"BK c #406FA9",
"BL c #4168BB",
"BM c #4F6BBC",
"BN c #4471AB",
"BO c #4976AD",
"BP c #4673B1",
"BQ c #4B76B5",
"BR c #4E7CB5",
"BS c #6479B7",
"BT c #5B7EC4",
"BU c #5C78C8",
"BV c #607CC8",
"BW c #00FF66",
"BX c #1CAD87",
"BY c #31A395",
"BZ c #4981AB",
"CA c #5B87BB",
"CB c #42A0A0",
"CC c #4AA3A5",
"CD c #57AFAA",
"CE c #5BADAD",
"CF c #58B7A9",
"CG c #758FBA",
"CH c #60B7AE",
"CI c #5980C1",
"CJ c #6381C5",
"CK c #6180C8",
"CL c #6D8AC3",
"CM c #6889C8",
"CN c #6D95C4",
"CO c #6A97C9",
"CP c #7088C1",
"CQ c #728ECF",
"CR c #758CD0",
"CS c #729FCF",
"CT c #7B9EC9",
"CU c #7E95D1",
"CV c #7E9AD1",
"CW c #7DA1CB",
"CX c #45C79A",
"CY c #4DC99F",
"CZ c #FF1301",
"DA c #FF1B03",
"DB c #FF1C09",
"DC c #FF2106",
"DD c #FF2508",
"DE c #FF2B0A",
"DF c #FF2F10",
"DG c #FF310B",
"DH c #F53D1F",
"DI c #FF3213",
"DJ c #FF361C",
"DK c #FF3A1D",
"DL c #FF3D20",
"DM c #FF6C5C",
"DN c #FF7C6C",
"DO c #8194CB",
"DP c #839CD4",
"DQ c #8D9DD0",
"DR c #88A4C9",
"DS c #8EA9CC",
"DT c #93ADCE",
"DU c #9EAACC",
"DV c #91A6D9",
"DW c #9DB5D3",
"DX c #AFB7C4",
"DY c #A1B5D4",
"DZ c #A7B4DA",
"EA c #ACB6D4",
"EB c #AAB6D9",
"EC c #AFBBDF",
"ED c #B1BBD6",
"EE c #A5B4E1",
"EF c #AABBE1",
"EG c #B3C6DD",
"EH c #BFD3E1",
"EI c #DD9B92",
"EJ c #D19CA4",
"EK c #DD9BB3",
"EL c #D5B9B4",
"EM c #ECB0A5",
"EN c #C9CFDF",
"EO c #DACFCF",
"EP c #DAD0CF",
"EQ c #DCD3D2",
"ER c #DBD0DD",
"ES c #D8DADD",
"ET c #C2C7E1",
"EU c #C4CFE4",
"EV c #CCD2E1",
"EW c #CBD4EC",
"EX c #CDD9E9",
"EY c #CCD7F0",
"EZ c #D0DAE5",
"FA c #DBDEE7",
"FB c #DFE0E3",
"FC c #DCE2EF",
"FD c #DCE0F0",
"FE c #E6D7D4",
"FF c #E0D8DB",
"FG c #E5DAE0",
"FH c #E1E4E7",
"FI c #E1E4EA",
"FJ c #E5E8EB",
"FK c #ECEBEC",
"FL c #E6ECF3",
"FM c #EEEFF3",
"FN c #E5F6F1",
"FO c #EDF3F4",
"FP c #E9FAF3",
"FQ c #F2F2F3",
"FR c #F1F5F9",
"FS c #F5F8FB",
"FT c #FEFEFE",
"FU c #000000",
"FV c #FFFFFF",
"FTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTBBBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBBBBBBBBBBBB",
"FTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTBBBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWCY",
"FTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFPBCBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWCY",
"FTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFNBCBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWCY",
"FTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFNBCBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWCY",
"FTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFNBCBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWCY",
"FTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFNBCBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWCY",
"FTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFOBBCECECECECECDCXBYBYBYBYBYBYBYCCCFCFCFCFCFCFBZ",
"FTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTEXDWDYDWDYDWDWCBBBBXBXBXBXBXBXBBDRDTDTDTDTDTDR",
"FTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTCHBXBWBWBWBWBWBWBOFLFTFTFTFTFTFT",
"FTFTFTFTFTFTFTFTFTFTEQEOEOEPEPEPEPEPEPEPEQEQEQFKFTFTFTCHBXBWBWBWBWBWBWBNFRFTFTFTFTFTFT",
"FTFTFTFTFTFTFTFTFTFTCZCZDBDBDDDDDFDEDFDFDIDIDFEIFTFTFTCHBXBWBWBWBWBWBWBEFSFTFTFTFTFTFT",
"FTFTFTFTFTFTFTFTFTFTCZCZCZDADADBDDDDDEDEDEDEDEEIFTFTFTCHBXBWBWBWBWBWBWBFFSFTFTFTFTFTFT",
"FTFTFTFTFTFTFTFTFTFTCZCZCZDADADDDDDEDEDEDEDEDDEIFTFTFTCHBXBWBWBWBWBWBWBEFSFTFTFTFTFTFT",
"FTFTFTFTFTFTFTFTFTFTCZCZCZDADCDCDEDEDEDGDGDEDEEIFTFTFTCHBXBWBWBWBWBWBWBKFQFTFTFTFTFTFT",
"FTFTFTFTFTFTFTFTFTFSCZCZCZDADCDDDEDEDGDGDEDEDDEIEUDVECEHBBBFBNBEBNBEBKBBFTFTFTFTFTFTFT",
"FTFTFTFTFTFTFTFTFTFTCZCZDADDDCDEDEDGDGDGDGDEDEEKAYADAXFQFSFOFSFOFSFQFSFSFTFTFTFTFTFTFT",
"FTFTFTFTFTFTFTFTFTFTCZCZDADADJFEFEFEFEFGFEFEFEERAPAHAKENFTFTFICUFIFTFTFTFTFTFTFTFTFTFT",
"FTFTFTFTFTFTFTFTFTFTCZCZDADCDKFTFTFTFIAXCTESFQDXAMAKAIBTEZEFAJAAAFFMFTFTFTFTFTFTFTFTFT",
"FTFTFTFTFTFTFTFTFTFTCZDADADDDKFTFTFTCVAIAKAQBIARAPAMAKAIAJADACAAAZFTFTFTFTFTFTFTFTFTFT",
"BBBBBBBBBBBBBBBBEGFSCZDADADDDIELELELERARAMAPAQAQAQAQAMAIAHAGADACENFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTCZDADCDCDEDEDGDGEMCGAPAQBABABDBQBPAPAHAGADASFQFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTCZDADCDCDEDEDGDGEMEUAQAQBDCNFBFTFTFHCMADADACEDFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTCZDADCDCDEDKDKDHEJCAAMAQBFFOFTFTFTFTFJAHADAAAAAEBVEYFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTCZDADCDCDKFQEAAUAKAKAMAQCWFTFTFTFTFTFTCJACAAAAAAAACRFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTCZDCDCDEDKFTCJADAHAIAMAMCTFTFTFTFTFTFTCKABABAAAAAOEEFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTCZDADCDCDKFTDYAXANAHAIAIBGFQFTFTFTFTFQAEABAAAOEAFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTCZDCDCDCDKFTFTFQFHDYAHAHAHCLFTFTFTFTCPABAAAAEWFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTCZDADCDCDKFTFTFTFTFTASADAGADBLDPDPAZABAAAAAADVFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTCZDCDCDCDKFTFTFTFTFCADADADADABADABABAAAAAAAAAAFAFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTCZDADCDCDKFTFTFTFTBMAAABABABABAAAAAAAAAEAAAAAACQFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTCZDADCDCDJFTFTFTFKAOAAACBSDUAOAAAAAADOFTEAAZALETFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTDMDMDMDMDNFTFTFTFTFABUFLFTFTEWAAAAAAFJFTFTFSFKFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTASAAAZFTFTFTFTFTFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCTDRFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTDQAVDZFTFTFTFTFTFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCNBBBEBNBEBNBFBFBNFSFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCABNCNCNCOCOCOCOBEFLFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCABRCSCSCSCSCSCSBOFLFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCABRCSCSCSCSCSCSBOFLFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCABRCSCSCSCSCSCSBNFOFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCOCABRCSCSCSCSCSCSBOFLFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFT",
"BBCSCSCSCSCSCSCABRCSCSCSCSCSCSBNFLFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFT",
"BBCWCWCWCWCWCWBZBECWCWCWCWCWCWBBFLFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFTFT",
"XPMENDEXT"
};  
  '''
  MenuText = "heapsOstuff WB"
  ToolTip = "heapsOstuff workbench"
  def Initialize(self):
    import CommandsHeap
    Log ('Loading heapsOstuff: done\n')
    list1=["mergeThing","heapsManager"]
    self.appendToolbar('heapsOstuff',list1)
    self.appendMenu(["Heaps of Stuff"],list1)
    pass

  def Activated(self):
    import FreeCAD, FreeCADGui, heaps
    FreeCAD.__activeHeap__=heaps.heap()
    Msg('Created variable in FreeCAD module:\n__activeHeap__\n')
    return

  def Deactivated(self):
    del FreeCAD.__activeHeap__
    Msg('Deleted variable in FreeCAD module:\n__activeHeap__\n')
    return

Gui.addWorkbench(heapsOstuffWorkbench)
